// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyp3KT3WqZnT9tANcwvCpgC_NyzZ3l_Cs',
    appId: '1:134815181682:web:02611dbd4dfbf322b20beb',
    messagingSenderId: '134815181682',
    projectId: 'reunioes-6e76e',
    authDomain: 'reunioes-6e76e.firebaseapp.com',
    databaseURL: 'https://reunioes-6e76e-default-rtdb.firebaseio.com',
    storageBucket: 'reunioes-6e76e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhjmeZy0WpPXGloPofmm-mbq5LTWpLP00',
    appId: '1:134815181682:android:ae9b425e6cc7d74db20beb',
    messagingSenderId: '134815181682',
    projectId: 'reunioes-6e76e',
    databaseURL: 'https://reunioes-6e76e-default-rtdb.firebaseio.com',
    storageBucket: 'reunioes-6e76e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqxeUuP_5hOSG-H_k4b2Oh9w1F67db6DA',
    appId: '1:134815181682:ios:8708f0101bc07300b20beb',
    messagingSenderId: '134815181682',
    projectId: 'reunioes-6e76e',
    databaseURL: 'https://reunioes-6e76e-default-rtdb.firebaseio.com',
    storageBucket: 'reunioes-6e76e.appspot.com',
    iosBundleId: 'com.example.meetings',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqxeUuP_5hOSG-H_k4b2Oh9w1F67db6DA',
    appId: '1:134815181682:ios:aa1f03b80e2d9b86b20beb',
    messagingSenderId: '134815181682',
    projectId: 'reunioes-6e76e',
    databaseURL: 'https://reunioes-6e76e-default-rtdb.firebaseio.com',
    storageBucket: 'reunioes-6e76e.appspot.com',
    iosBundleId: 'com.example.meetings.RunnerTests',
  );
}
